name: build

on: push

jobs:
  build:
    name: build the application
    runs-on: ubuntu-latest
    container: nixos/nix:2.23.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: nix build
