name: build

on: push

jobs:
  build:
    name: build the application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run build in Nix container
        uses: addnab/docker-run-action@v3
        with:
          image: nixos/nix:2.23.0
          options: -v ${{ github.workspace }}:/work -w /work
          run: |
            ls -la
            nix --extra-experimental-features nix-command --extra-experimental-features flakes build

      - name: Verify result
        run: ls -la result
