name: build

on: push

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run build in Nix container
        uses: addnab/docker-run-action@v3
        with:
          image: nixos/nix:2.23.0
          options: -v ${{ github.workspace }}:/workspace -v tmp-nix-store:/nix/store -w /workspace
          run: |
            git config --global --add safe.directory /workspace
            nix --extra-experimental-features nix-command --extra-experimental-features flakes build -L --show-trace
            cp -r result/bin/template /workspace

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: application-binary
          path: ${{ github.workspace }}/template
          retention-days: 1

  test:
    name: test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download binary
        uses: actions/download-artifact@v4
        with:
          name: application-binary
          path: ./template

      - name: Run binary
        run: |
          chmod +x template
          ./template
