name: build

on: push

jobs:
  build:
    name: build the application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run build in Nix container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            nixos/nix:2.23.0 \
            sh -c "chown -R 1000:1000 /workspace && nix --extra-experimental-features nix-command --extra-experimental-features flakes build"
